### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by pfsq** [Pybonacci/pybo-wp-theme#2]
Los videos de YouTube se insertan desproporcionados:
![youtube1](https://cloud.githubusercontent.com/assets/5616935/3731840/ab4496d0-16f2-11e4-9c83-957af5569e0e.png)
![youtube2](https://cloud.githubusercontent.com/assets/5616935/3731842/b0ed7b56-16f2-11e4-8cc8-50bac933e326.png)

**Comment by astrojuanlu** [comment]
Confirmado en mi copia local. Voy a inspeccionar esto.

**Comment by astrojuanlu** [comment]
Parece que debe ser algún problema con la aritmética en el lado YouTube (!) porque no encuentro en el código WordPress dónde se fija el alto del vídeo. Como medida provisional se puede fijar un `max-height` en el CSS de 400 px pero haría falta que alguien mirase esto con un poco más de detalle. Hago el cambio y cierro la incidencia de momento.

**Comment by kikocorreoso** [comment]
Con jetpack se puede embeber con el mismo estilo que usa wp.com, e.g., [youtube ...]

http://jetpack.me/support/shortcode-embeds/
